# Generated by Django 5.1.2 on 2024-11-05 10:09

import django.db.models.deletion
import startup_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='startup_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=100)),
                ('Logo', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=500)),
                ('funding_needs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity_offered', models.FloatField()),
                ('pitch_deck', models.FileField(upload_to='documents/', validators=[startup_profile.models.validate_file_size])),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_profile.industry')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_profile.stage')),
            ],
        ),
        migrations.CreateModel(
            name='startup_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor_profile.investor_profile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_profile.startup_profile')),
            ],
        ),
    ]
