# Generated by Django 5.1.2 on 2024-11-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor_profile', '0001_initial'),
        ('startup_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_profile.startup_profile'),
        ),
        migrations.AddField(
            model_name='investor_profile',
            name='investment_preferences',
            field=models.ManyToManyField(to='startup_profile.industry'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor_profile.investor_profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='investor_profile.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='startup_profile.startup_profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='investor_profile.investor_profile'),
        ),
    ]
